"""Build supplementary Figure S5: a two-panel merge of the simulation localisation
figures (panel A = localisation / "where detections land"; panel B = localisation
accuracy with vs without HRF filtering).

The manuscript's Figure S5 is this side-by-side composite. The two source panels
are generated by simulator/diagnostic_validation/export_paper_figures.py into
figures/unused/ (they are not standalone display items); this script stitches
them into figures/paper/figS5_sim_localization_merged.{png,pdf}.

Pure Pillow (no matplotlib). Layout: open both RGB; pad the shorter panel to the
taller height with white; 30 px horizontal gap; a 46 px white header strip above
both; paste A at (0, 46) and B at (widthA + 30, 46); draw bold "A" at (14, 6) and
"B" at (widthA + 30 + 14, 6) in DejaVuSans-Bold 38 pt (falling back to Pillow's
default font); save at 300 dpi PNG plus a PDF copy to match the other paper
figures.

Usage:
  python scripts/make_figS5_localization.py [--panel-a A.png] [--panel-b B.png]
                                            [--out figS5.png]
"""
from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
DEF_A = ROOT / "figures/unused/figS7_sim_localization.png"
DEF_B = ROOT / "figures/unused/figS8_sim_hrf_localization.png"
DEF_OUT = ROOT / "figures/paper/figS5_sim_localization_merged.png"

HEADER = 46
GAP = 30
LABEL_PT = 38
DPI = 300


def _load_bold_font(size):
    """DejaVuSans-Bold at `size`, with graceful fallbacks (incl. the copy that
    ships with matplotlib), else Pillow's built-in default."""
    candidates = [
        "DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/Library/Fonts/DejaVuSans-Bold.ttf",
    ]
    try:  # matplotlib bundles DejaVuSans-Bold
        import matplotlib
        candidates.append(
            str(Path(matplotlib.get_data_path()) / "fonts/ttf/DejaVuSans-Bold.ttf"))
    except Exception:
        pass
    for c in candidates:
        try:
            return ImageFont.truetype(c, size)
        except Exception:
            continue
    return ImageFont.load_default()


def _pad_to_height(im, h):
    if im.height == h:
        return im
    canvas = Image.new("RGB", (im.width, h), "white")
    canvas.paste(im, (0, 0))
    return canvas


def merge(panel_a, panel_b, out):
    a = Image.open(panel_a).convert("RGB")
    b = Image.open(panel_b).convert("RGB")
    h = max(a.height, b.height)
    a, b = _pad_to_height(a, h), _pad_to_height(b, h)

    W, H = a.width + GAP + b.width, HEADER + h
    canvas = Image.new("RGB", (W, H), "white")
    canvas.paste(a, (0, HEADER))
    canvas.paste(b, (a.width + GAP, HEADER))

    draw = ImageDraw.Draw(canvas)
    font = _load_bold_font(LABEL_PT)
    draw.text((14, 6), "A", fill="black", font=font)
    draw.text((a.width + GAP + 14, 6), "B", fill="black", font=font)

    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(out, "PNG", dpi=(DPI, DPI))
    pdf = out.with_suffix(".pdf")
    canvas.save(pdf, "PDF", resolution=float(DPI))
    print(f"wrote {out}  ({W} x {H} px @ {DPI} dpi)")
    print(f"wrote {pdf}")
    return (W, H)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--panel-a", default=str(DEF_A), help="localisation figure (A)")
    ap.add_argument("--panel-b", default=str(DEF_B), help="HRF localisation figure (B)")
    ap.add_argument("--out", default=str(DEF_OUT), help="output PNG (PDF alongside)")
    args = ap.parse_args()
    merge(args.panel_a, args.panel_b, args.out)


if __name__ == "__main__":
    main()
